<?php

use Illuminate\Database\Seeder;

class ItemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('items')->insert([
            [
                'item_name' => 'IPhone',
                'item_desc' => 'Smart Phone I7+',
                'item_details' => '64GB storage, 4GB RAM',
                'item_price' => '990.50',
                'item_pic' => '/apple/iphone.jpg',
                'brand_id' => '1',
                'cat_id' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'MacBook',
                'item_desc' => 'Latest MacBook Generation 5',
                'item_details' => '64GB storage, 4GB RAM',
                'item_price' => '1880.00',
                'item_pic' => '/apple/macbook.jpg',
                'brand_id' => '1',
                'cat_id' => '2',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Tablet',
                'item_desc' => 'Tablet',
                'item_details' => '64GB storage, 4GB RAM',
                'item_price' => '590.90',
                'item_pic' => '/apple/tablet.jpg',
                'brand_id' => '1',
                'cat_id' => '3',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Music Player',
                'item_desc' => 'Music Player',
                'item_details' => '128GB storage',
                'item_price' => '90.00',
                'item_pic' => '/sandisk/music.jpg',
                'brand_id' => '4',
                'cat_id' => '6',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Smart Watch',
                'item_desc' => 'Bluetooth connection',
                'item_details' => '8GB storage, water proof',
                'item_price' => '190.00',
                'item_pic' => '/apple/watch.jpg',
                'brand_id' => '1',
                'cat_id' => '4',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Earphone',
                'item_desc' => 'Earpods',
                'item_details' => 'Earpods with 3.5mm headphone plug, come with casing',
                'item_price' => '199.00',
                'item_pic' => '/apple/earpods.jpg',
                'brand_id' => '1',
                'cat_id' => '9',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Desktop',
                'item_desc' => 'iMac',
                'item_details' => '27 inch display,3.0GHz',
                'item_price' => '1799.00',
                'item_pic' => '/apple/imac.jpg',
                'brand_id' => '1',
                'cat_id' => '6',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Ipod',
                'item_desc' => 'Music Player',
                'item_details' => '32GB, comes with earphones',
                'item_price' => '194.99',
                'item_pic' => '/apple/ipod.png',
                'brand_id' => '1',
                'cat_id' => '6',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'USB',
                'item_desc' => 'USB 64GB, 3.0',
                'item_details' => '64GB storage, 3.0 Port',
                'item_price' => '88.00',
                'item_pic' => '/sandisk/USB.jpg',
                'brand_id' => '4',
                'cat_id' => '5',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Harddrive',
                'item_desc' => 'Sandisk hardrive',
                'item_details' => '1 TB, extrem portable SSD',
                'item_price' => '250.00',
                'item_pic' => '/sandisk/hardrive.jpg',
                'brand_id' => '4',
                'cat_id' => '5',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Camera',
                'item_desc' => 'Sandisk Camera',
                'item_details' => '32GB/ 2channels, full HD',
                'item_price' => '1588.00',
                'item_pic' => '/sandisk/camera.jpg',
                'brand_id' => '4',
                'cat_id' => '12',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Speaker',
                'item_desc' => 'Portable Bluetooth speaker',
                'item_details' => 'Sony SRS- XB10, Waterproof',
                'item_price' => '58.00',
                'item_pic' => '/sony/speaker.jpg',
                'brand_id' => '5',
                'cat_id' => '7',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Fridge',
                'item_desc' => 'Double door fridge',
                'item_details' => '2 years warranty',
                'item_price' => '9500.00',
                'item_pic' => '/sony/fridge.jpg',
                'brand_id' => '5',
                'cat_id' => '8',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Headphone',
                'item_desc' => 'Bluetooth headphone',
                'item_details' => 'Portable, light weigth, last for 4 hours',
                'item_price' => '125.00',
                'item_pic' => '/sony/headphone.jpg',
                'brand_id' => '5',
                'cat_id' => '9',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Laptop',
                'item_desc' => '16 inch laptop',
                'item_details' => '32GB RAM, Windows 10',
                'item_price' => '1850.00',
                'item_pic' => '/sony/laptop.jpg',
                'brand_id' => '5',
                'cat_id' => '2',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Mobile Phone',
                'item_desc' => 'Xperia 5',
                'item_details' => '21.9 Cinema wide, 6.1" FHD',
                'item_price' => '850.00',
                'item_pic' => '/sony/mobile.jpg',
                'brand_id' => '5',
                'cat_id' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Desktop',
                'item_desc' => 'Falt screen',
                'item_details' => '32 inch, 2 years warranty',
                'item_price' => '2500.00',
                'item_pic' => '/sony/monitor.jpg',
                'brand_id' => '5',
                'cat_id' => '10',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Smart watch',
                'item_desc' => 'Smart watch',
                'item_details' => 'waterproof, 2 years warranty',
                'item_price' => '1500.00',
                'item_pic' => '/sony/smartwatch.jpg',
                'brand_id' => '5',
                'cat_id' => '4',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Tablet',
                'item_desc' => 'Sony tablet',
                'item_details' => '16GB RAM, 9 inch screen',
                'item_price' => '1250.00',
                'item_pic' => '/sony/tablet.jpg',
                'brand_id' => '5',
                'cat_id' => '3',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'TV',
                'item_desc' => 'Sony TV',
                'item_details' => '52 inch, 2 years warranty',
                'item_price' => '2500.00',
                'item_pic' => '/sony/tv.jpg',
                'brand_id' => '5',
                'cat_id' => '11',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Walkman',
                'item_desc' => 'Sony Walkman',
                'item_details' => 'portable, 2 years warranty',
                'item_price' => '150.00',
                'item_pic' => '/sony/walkman.jpg',
                'brand_id' => '5',
                'cat_id' => '6',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Camera',
                'item_desc' => 'Sony Camera',
                'item_details' => 'Sony Alpha a6400 Mirrorless camera',
                'item_price' => '150.00',
                'item_pic' => '/sony/camera.jpg',
                'brand_id' => '5',
                'cat_id' => '12',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Camera',
                'item_desc' => 'Gopro Camera',
                'item_details' => 'waterproof, 52 pixels,2 years warranty',
                'item_price' => '980.00',
                'item_pic' => '/gopro/camera.jpg',
                'brand_id' => '2',
                'cat_id' => '12',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Hardrive',
                'item_desc' => 'Gopro hardrive',
                'item_details' => '1TB,6,000mAh',
                'item_price' => '250.00',
                'item_pic' => '/gopro/hardrive.jpg',
                'brand_id' => '2',
                'cat_id' => '5',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Cable',
                'item_desc' => 'Gopro HDMI cable',
                'item_details' => '2 meters',
                'item_price' => '25.00',
                'item_pic' => '/gopro/hdmi.jpg',
                'brand_id' => '2',
                'cat_id' => '13',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Smart watch',
                'item_desc' => 'Gopro smart watch',
                'item_details' => 'Waterproof, last for 6 hours if fully charged',
                'item_price' => '1250.00',
                'item_pic' => '/gopro/watch.jpg',
                'brand_id' => '2',
                'cat_id' => '4',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Fridge',
                'item_desc' => 'LG double door fridge',
                'item_details' => '2 years warranty, ice cube maker',
                'item_price' => '6500.00',
                'item_pic' => '/lg/fridge.jpg',
                'brand_id' => '3',
                'cat_id' => '8',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'External Harddrive',
                'item_desc' => 'LG portable hardrive',
                'item_details' => '1 terabyte',
                'item_price' => '180.00',
                'item_pic' => '/lg/harddrive.jpg',
                'brand_id' => '3',
                'cat_id' => '5',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Headset',
                'item_desc' => 'LG headset',
                'item_details' => 'Bluetooth, last to 4 years fully charged',
                'item_price' => '45.00',
                'item_pic' => '/lg/headset.jpg',
                'brand_id' => '3',
                'cat_id' => '9',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Home theater system',
                'item_desc' => 'LG home theater system',
                'item_details' => 'With sound woofer, 4 speakers',
                'item_price' => '1520.00',
                'item_pic' => '/lg/theater.jpg',
                'brand_id' => '3',
                'cat_id' => '6',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Laptop',
                'item_desc' => 'LG 16 inch laptop',
                'item_details' => '32GB harddrive, Windows 12, antivirus installed',
                'item_price' => '1420.00',
                'item_pic' => '/lg/laptop.jpg',
                'brand_id' => '3',
                'cat_id' => '2',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Monitor',
                'item_desc' => 'LG falt screen',
                'item_details' => 'flat screen, 18 inch',
                'item_price' => '850.00',
                'item_pic' => '/lg/monitor.jpg',
                'brand_id' => '3',
                'cat_id' => '10',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'Smart watches',
                'item_desc' => 'LG smart watch',
                'item_details' => 'Android OS, 2 years warranty',
                'item_price' => '1850.00',
                'item_pic' => '/lg/watch.jpg',
                'brand_id' => '3',
                'cat_id' => '4',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'LG TV screen',
                'item_desc' => 'LG TV screen',
                'item_details' => '42 inch, flat screen',
                'item_price' => '1800.00',
                'item_pic' => '/lg/tv.jpg',
                'brand_id' => '3',
                'cat_id' => '11',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'LG USB',
                'item_desc' => 'LG USB',
                'item_details' => '32 GB',
                'item_price' => '45.00',
                'item_pic' => '/lg/usb.jpg',
                'brand_id' => '3',
                'cat_id' => '5',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'LG Mobile phone',
                'item_desc' => 'LG Mobile phone',
                'item_details' => '16GB, waterproof',
                'item_price' => '785.00',
                'item_pic' => '/lg/phone.jpg',
                'brand_id' => '3',
                'cat_id' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'item_name' => 'LG Tablet',
                'item_desc' => 'LG Tablet',
                'item_details' => '10 inch',
                'item_price' => '785.00',
                'item_pic' => '/lg/tablet.jpg',
                'brand_id' => '3',
                'cat_id' => '3',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ]
        ]);
    }
}
